version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: jobscraper-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
    volumes:
      - n8n_data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/workflows
      - ./scrapers:/home/node/scrapers
      - ./config:/home/node/config
    networks:
      - jobscraper-network

volumes:
  n8n_data:

networks:
  jobscraper-network:
    driver: bridge